### ISSUE TITLE
question

### ISSUE THREAD

**Issue by tidiview** [fredrikekelund/grav-plugin-resize-images#1]
thank you for this nice plugin.

I am not using the admin panel at all: can I use this plugin anyway?

If so, could you explain in README file how to use it without it?

Thanks in advance

**Comment by fredrikekelund** [comment]
Hey, thanks for the kind words! My ambition is to add a CLI to this plugin to make it simple to generate image alternatives for individual pages, or all pages.

You're welcome to submit a PR if you like, otherwise I hope to get around to this over the coming weeks!

**Comment by tidiview** [comment]
Thanks for your answer and sorry for the delay.

I apologize: I don't have the basic technical knowledge to be able to submit a PR.

I have seen that in the future version of GRAV, there will be something about derivatives: it looks very interisting, while I can't see yet very well how I will be able to use it. Probably, it has to be implemented with lazyload...

So, I understand that I can't not use your plugin for the moment (sorry to be a little heavy in communication), but that in a near future, it will be possible by CLI.
(I guess CLI means Command Line Interface here probably)

Is there a particular reason why you don't release your plugin on getgrav.org?

Thanks again ♪ I will look foward as soon as CLI will be available.

If you have some suggestions, please feel free to let me know.

**Comment by fredrikekelund** [comment]
I opened #6 to track progress on implementing a CLI. Feel free to subscribe to that ticket for updates :)
