### ISSUE TITLE
Error: Call to a member function resize() on boolean

### ISSUE THREAD

**Issue by MIKAGMR** [fredrikekelund/grav-plugin-resize-images#2]
Hi,

I have tried your plugin and when I want to save a page in the admin panel I get this error message:

```
Error 
…/user/plugins/resize-images/resize-images.php:72
``` 

This error happens when I use an image file without `@[density-ratio]x` in the filename.

**Comment by fredrikekelund** [comment]
Hmm, this might be due to some flawed logic in how the "image adapter" (the module that does the actual resizing) is selected currently.

Could you try to change the plugin configuration so that the adapter preference is set to "GD" instead of "Imagick" (is it isn't already)?

**Comment by MIKAGMR** [comment]
The adapter preference was set to GD, but I tested it with Imagick the plugin runs fine

**Comment by fredrikekelund** [comment]
Great! I should probably still have a look at what caused this. Do you know if you have the GD extension installed? And if you could post the full stack trace of the error you got as well, that'd be very helpful!

**Comment by MIKAGMR** [comment]
I don't know....I am not in front of my workstation anymore, but I have used [valet](https://laravel.com/docs/5.3/valet) to test grav...

**Comment by MIKAGMR** [comment]
I have tested it (apache and valet) and I can't reproduce the error anymore.
