### ISSUE TITLE
Call to a member function resize() on boolean

### ISSUE THREAD

**Issue by gour** [fredrikekelund/grav-plugin-resize-images#4]
Hello,

I've started working with Grav and your plugin is very lovely add-on to simplify image issues.

After installing it, I'm trying it on my old blog where I have line like:

```
![alt text](image.jpg) {.center}
```

but I get:

```
Error thrown with message "Call to a member function resize() on boolean"

Stacktrace:
#23 Error in /var/www/html/net.local/user/plugins/resize-images/resize-images.php:72
#22 Grav\Plugin\ResizeImagesPlugin:resizeImage in /var/www/html/net.local/user/plugins/resize-images/resize-images.php:115
#21 Grav\Plugin\ResizeImagesPlugin:onAdminSave in /var/www/html/net.local/vendor/symfony/event-dispatcher/EventDispatcher.php:184
#20 call_user_func in /var/www/html/net.local/vendor/symfony/event-dispatcher/EventDispatcher.php:184
#19 Symfony\Component\EventDispatcher\EventDispatcher:doDispatch in /var/www/html/net.local/vendor/symfony/event-dispatcher/EventDispatcher.php:46
#18 Symfony\Component\EventDispatcher\EventDispatcher:dispatch in /var/www/html/net.local/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php:23
#17 RocketTheme\Toolbox\Event\EventDispatcher:dispatch in /var/www/html/net.local/system/src/Grav/Common/Grav.php:272
#16 Grav\Common\Grav:fireEvent in /var/www/html/net.local/user/plugins/admin/classes/controller.php:2003
#15 Grav\Plugin\AdminController:taskSave in /var/www/html/net.local/user/plugins/admin/classes/controller.php:188
#14 call_user_func in /var/www/html/net.local/user/plugins/admin/classes/controller.php:188
#13 Grav\Plugin\AdminController:execute in /var/www/html/net.local/user/plugins/admin/admin.php:324
#12 Grav\Plugin\AdminPlugin:initializeController in /var/www/html/net.local/user/plugins/admin/admin.php:371
#11 Grav\Plugin\AdminPlugin:onPagesInitialized in /var/www/html/net.local/vendor/symfony/event-dispatcher/EventDispatcher.php:184
#10 call_user_func in /var/www/html/net.local/vendor/symfony/event-dispatcher/EventDispatcher.php:184
#9 Symfony\Component\EventDispatcher\EventDispatcher:doDispatch in /var/www/html/net.local/vendor/symfony/event-dispatcher/EventDispatcher.php:46
#8 Symfony\Component\EventDispatcher\EventDispatcher:dispatch in /var/www/html/net.local/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php:23
#7 RocketTheme\Toolbox\Event\EventDispatcher:dispatch in /var/www/html/net.local/system/src/Grav/Common/Grav.php:272
#6 Grav\Common\Grav:fireEvent in /var/www/html/net.local/system/src/Grav/Common/Processors/PagesProcessor.php:25
#5 Grav\Common\Processors\PagesProcessor:process in /var/www/html/net.local/system/src/Grav/Common/Grav.php:121
#4 Grav\Common\Grav:Grav\Common\{closure} in /var/www/html/net.local/system/src/Grav/Common/Grav.php:358
#3 Grav\Common\Grav:Grav\Common\{closure} in /var/www/html/net.local/system/src/Grav/Common/Grav.php:334
#2 call_user_func_array in /var/www/html/net.local/system/src/Grav/Common/Grav.php:334
#1 Grav\Common\Grav:__call in /var/www/html/net.local/system/src/Grav/Common/Grav.php:122
#0 Grav\Common\Grav:process in /var/www/html/net.local/index.php:45
```

Any hint?

**Comment by fredrikekelund** [comment]
Hmm yes, this seems to be a problem with the selection of an appropriate "image resizing adapter" (the module that does the actual resizing). Can you check the plugin page in the Grav admin and see what the image adapter setting is set to? You can try to change that setting, and if that doesn't work, you'll need to install either GD or Imagick on the server. If you have a choice, Imagick is preferable

**Comment by gour** [comment]
> Can you check the plugin page in the Grav admin and see what the image adapter setting is set to? 

It was set to "Imagick", but PHP extension was not installed.

> You can try to change that setting, 

Changing to GD which was installed did help...

> and if that doesn't work, you'll need to install either GD or Imagick on the server. If you have a choice, Imagick is preferable

At the moment I'm working on my desktop machine, so installed Imagick as well.

Fortunately enough, on production server where I don't have root access, both adapters are installed. :-)

However, I still have to wrap my head against this `srcset` feature. ;)

**Comment by fredrikekelund** [comment]
Good to hear you managed to solve it! I hope to improve the way that this plugin selects an image adapter, and I might also add a warning when it falls back to one that isn't selected. I opened #5 to track progress on that.

I know I had some trouble understanding srcset initially as well, but the article that's also linked in the Grav docs is actually a really good resource – http://ericportis.com/posts/2014/srcset-sizes/. It's a 10-15 minute read, but totally worth it
