### ISSUE TITLE
Remove original size image

### ISSUE THREAD

**Issue by anthubbard** [fredrikekelund/grav-plugin-resize-images#8]
Hi Fredrik,

This is not an issue - just a question - is it possible to remove or don't add at all the original image once it's done the resizes?

Thanks,

**Comment by fredrikekelund** [comment]
Hi @anthubbard, thanks for the suggestion and sorry about the slow response! I've just pushed a version 0.2.1 of the plugin that adds an option to enable this (disabled by default). Let me know if you have any issues with it!

**Comment by anthubbard** [comment]
This works perfect! thank you so much.

Cheers
